apiVersion: batch/v1
kind: Job
metadata:
  name: mini-job
spec:
  completions: 500
  parallelism: 500
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: date
          image: alpine:latest
          workingDir: /app
          command: ["/bin/sh", "-c", "date"]
