apiVersion: batch/v1
kind: Job
metadata:
  name: blender-render-job
spec:
  completions: 100
  parallelism: 1
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: blender
        image: blender-job
        workingDir: /app
        args: ["--background", "myfile.blend", "-E", "CYCLES", "--render-output", "./frame-$(JOB_COMPLETION_INDEX).png", "--render-frame", "$(JOB_COMPLETION_INDEX)"]
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4