apiVersion: batch/v1
kind: Job
metadata:
  name: blender-render-job
spec:
  completions: 100
  parallelism: 100
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: blender
          image: petroniuss/lcs-blender:v2
          workingDir: /app
          args:
            [
              "--background",
              "myfile.blend",
              "-E",
              "CYCLES",
              "--render-output",
              "./frame-$(JOB_COMPLETION_INDEX).png",
              "--render-frame",
              "$(JOB_COMPLETION_INDEX)",
            ]
          resources:
            requests:
              memory: 1100Mi
